
apiVersion: v1
kind: Service
metadata:
  name: super-hero-test-service
  labels:
    app: super-hero-test-app
spec:
  type: LoadBalancer
  selector:
    matchLabels:
      app: super-hero-test-app
  ports:
    name: http
    port: 8080
    protocol: TCP
    targetPort: 8080